---
java_params: -Xms2048m -Xmx3328m
server_file_url: https://minecraft.curseforge.com/projects/sevtech-ages/files/2570735/download
ansible_ssh_private_key_file: ~/.ssh/mc_server.pem
timezone: America/Toronto

install_script: Install.sh
