---
aws_region: us-east-2
aws_instance_type: t2.medium

java_params: -Xms2048m -Xmx3328m
server_jar_url: https://launcher.mojang.com/mc/game/1.12.2/server/886945bfb2b978778c3a0288fd7fab09d315b25f/server.jar
ansible_ssh_private_key_file: ~/.ssh/mc_server.pem
timezone: America/Toronto
